# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import swordsec_pb2 as swordsec__pb2


class SwordsecStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetUserData = channel.stream_unary(
                '/swordsec.Swordsec/SetUserData',
                request_serializer=swordsec__pb2.UserData.SerializeToString,
                response_deserializer=swordsec__pb2.ProcessStatus.FromString,
                )


class SwordsecServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SetUserData(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SwordsecServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetUserData': grpc.stream_unary_rpc_method_handler(
                    servicer.SetUserData,
                    request_deserializer=swordsec__pb2.UserData.FromString,
                    response_serializer=swordsec__pb2.ProcessStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swordsec.Swordsec', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Swordsec(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SetUserData(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/swordsec.Swordsec/SetUserData',
            swordsec__pb2.UserData.SerializeToString,
            swordsec__pb2.ProcessStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
